schemaVersion: 2.2.2
metadata:
  name: ${{ values.repoName }}
components:
  - name: dotnet
    container:
      image: registry.access.redhat.com/ubi8/dotnet-80:8.0-13
      args: ["tail", "-f", "/dev/null"]
      mountSources: true
      env:
        - name: CONFIGURATION
          value: Debug
        - name: STARTUP_PROJECT
          value: app.csproj
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://*:8080
      endpoints:
        - name: https-dotnet80
          protocol: https
          targetPort: 8080
commands:
  - id: build
    exec:
      workingDir: ${PROJECT_SOURCE}/app
      commandLine: kill $(pidof dotnet); dotnet build -c $CONFIGURATION $STARTUP_PROJECT /p:UseSharedCompilation=false
      component: dotnet
      group:
        isDefault: true
        kind: build
  - id: run
    exec:
      workingDir: ${PROJECT_SOURCE}/app
      commandLine: dotnet run -c $CONFIGURATION --no-build --project $STARTUP_PROJECT --no-launch-profile
      component: dotnet
      group:
        isDefault: true
        kind: run